
var spineWasm = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(spineWasm = {})  {

var g;g||(g=typeof spineWasm !== 'undefined' ? spineWasm : {});var aa,ba;g.ready=new Promise((a,b)=>{aa=a;ba=b});var da=Object.assign({},g),q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);_scriptDir&&(q=_scriptDir);0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="";var ea=g.print||console.log.bind(console),v=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;var w;g.wasmBinary&&(w=g.wasmBinary);
var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&y("no native wasm support detected");var fa,ha=!1,ia,A,B,ja,C,D,ka,la;function ma(){var a=fa.buffer;g.HEAP8=ia=new Int8Array(a);g.HEAP16=B=new Int16Array(a);g.HEAP32=C=new Int32Array(a);g.HEAPU8=A=new Uint8Array(a);g.HEAPU16=ja=new Uint16Array(a);g.HEAPU32=D=new Uint32Array(a);g.HEAPF32=ka=new Float32Array(a);g.HEAPF64=la=new Float64Array(a)}var na,oa=[],pa=[],qa=[];function ra(){var a=g.preRun.shift();oa.unshift(a)}
var E=0,sa=null,F=null;function y(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";v(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function ta(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="spine.wasm";if(!ta(G)){var ua=G;G=g.locateFile?g.locateFile(ua,q):q+ua}function va(a){try{if(a==G&&w)return new Uint8Array(w);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function wa(a){return w||"function"!=typeof fetch?Promise.resolve().then(()=>va(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>va(a))}function xa(a,b,c){return wa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{v("failed to asynchronously prepare wasm: "+d);y(d)})}
function ya(a,b){var c=G;return w||"function"!=typeof WebAssembly.instantiateStreaming||ta(c)||"function"!=typeof fetch?xa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){v("wasm streaming compile failed: "+e);v("falling back to ArrayBuffer instantiation");return xa(c,a,b)}))}function za(a){for(;0<a.length;)a.shift()(g)}var Aa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Aa)return Aa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|k:(e&7)<<18|h<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function Ca(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var Da=void 0;function I(a){for(var b="";A[a];)b+=Da[A[a++]];return b}var J={},K={},Ea={};function Fa(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Ga(a,b){a=Fa(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Ha(a){var b=Error,c=Ga(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}var L=void 0;function M(a){throw new L(a);}var Ia=void 0;function Ja(a){throw new Ia(a);}
function O(a,b,c){function d(f){f=c(f);f.length!==a.length&&Ja("Mismatched type converter count");for(var l=0;l<a.length;++l)P(a[l],f[l])}a.forEach(function(f){Ea[f]=b});var e=Array(b.length),h=[],k=0;b.forEach((f,l)=>{K.hasOwnProperty(f)?e[l]=K[f]:(h.push(f),J.hasOwnProperty(f)||(J[f]=[]),J[f].push(()=>{e[l]=K[f];++k;k===h.length&&d(e)}))});0===h.length&&d(e)}
function P(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||M(`type "${d}" must have a positive integer typeid pointer`);if(K.hasOwnProperty(a)){if(c.ua)return;M(`Cannot register type '${d}' twice`)}K[a]=b;delete Ea[a];J.hasOwnProperty(a)&&(b=J[a],delete J[a],b.forEach(e=>e()))}function Ka(a){M(a.P.T.R.name+" instance already deleted")}var La=!1;function Ma(){}
function Na(a){--a.count.value;0===a.count.value&&(a.W?a.X.ba(a.W):a.T.R.ba(a.S))}function Oa(a,b,c){if(b===c)return a;if(void 0===c.U)return null;a=Oa(a,b,c.U);return null===a?null:c.ra(a)}var Pa={},Q=[];function Qa(){for(;Q.length;){var a=Q.pop();a.P.da=!1;a["delete"]()}}var R=void 0,S={};function Ra(a,b){for(void 0===b&&M("ptr should not be undefined");a.U;)b=a.fa(b),a=a.U;return S[b]}
function Sa(a,b){b.T&&b.S||Ja("makeClassHandle requires ptr and ptrType");!!b.X!==!!b.W&&Ja("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Ta(Object.create(a,{P:{value:b}}))}function Ta(a){if("undefined"===typeof FinalizationRegistry)return Ta=b=>b,a;La=new FinalizationRegistry(b=>{Na(b.P)});Ta=b=>{var c=b.P;c.W&&La.register(b,{P:c},b);return b};Ma=b=>{La.unregister(b)};return Ta(a)}function T(){}
function Ua(a,b,c){if(void 0===a[b].V){var d=a[b];a[b]=function(){a[b].V.hasOwnProperty(arguments.length)||M(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].V})!`);return a[b].V[arguments.length].apply(this,arguments)};a[b].V=[];a[b].V[d.ca]=d}}
function Va(a,b){g.hasOwnProperty(a)?(M(`Cannot register public name '${a}' twice`),Ua(g,a,a),g.hasOwnProperty(void 0)&&M("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].V[void 0]=b):g[a]=b}function Wa(a,b,c,d,e,h,k,f){this.name=a;this.constructor=b;this.$=c;this.ba=d;this.U=e;this.sa=h;this.fa=k;this.ra=f;this.wa=[]}
function Xa(a,b,c){for(;b!==c;)b.fa||M(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.fa(a),b=b.U;return a}function Ya(a,b){if(null===b)return this.ja&&M(`null is not a valid ${this.name}`),0;b.P||M(`Cannot pass "${Za(b)}" as a ${this.name}`);b.P.S||M(`Cannot pass deleted object as a pointer of type ${this.name}`);return Xa(b.P.S,b.P.T.R,this.R)}
function $a(a,b){if(null===b){this.ja&&M(`null is not a valid ${this.name}`);if(this.ia){var c=this.xa();null!==a&&a.push(this.ba,c);return c}return 0}b.P||M(`Cannot pass "${Za(b)}" as a ${this.name}`);b.P.S||M(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.ha&&b.P.T.ha&&M(`Cannot convert argument of type ${b.P.X?b.P.X.name:b.P.T.name} to parameter type ${this.name}`);c=Xa(b.P.S,b.P.T.R,this.R);if(this.ia)switch(void 0===b.P.W&&M("Passing raw pointer to smart pointer is illegal"),
this.Aa){case 0:b.P.X===this?c=b.P.W:M(`Cannot convert argument of type ${b.P.X?b.P.X.name:b.P.T.name} to parameter type ${this.name}`);break;case 1:c=b.P.W;break;case 2:if(b.P.X===this)c=b.P.W;else{var d=b.clone();c=this.ya(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ba,c)}break;default:M("Unsupporting sharing policy")}return c}
function ab(a,b){if(null===b)return this.ja&&M(`null is not a valid ${this.name}`),0;b.P||M(`Cannot pass "${Za(b)}" as a ${this.name}`);b.P.S||M(`Cannot pass deleted object as a pointer of type ${this.name}`);b.P.T.ha&&M(`Cannot convert argument of type ${b.P.T.name} to parameter type ${this.name}`);return Xa(b.P.S,b.P.T.R,this.R)}function bb(a){return this.fromWireType(C[a>>2])}
function V(a,b,c,d){this.name=a;this.R=b;this.ja=c;this.ha=d;this.ia=!1;this.ba=this.ya=this.xa=this.na=this.Aa=this.va=void 0;void 0!==b.U?this.toWireType=$a:(this.toWireType=d?Ya:ab,this.Z=null)}function cb(a,b){g.hasOwnProperty(a)||Ja("Replacing nonexistant public symbol");g[a]=b;g[a].ca=void 0}
function db(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=na.get(b).apply(null,c);return d}}function W(a,b){a=I(a);var c=a.includes("j")?db(a,b):na.get(b);"function"!=typeof c&&M(`unknown function pointer with signature ${a}: ${b}`);return c}var eb=void 0;function fb(a){a=gb(a);var b=I(a);X(a);return b}
function Y(a,b){function c(h){e[h]||K[h]||(Ea[h]?Ea[h].forEach(c):(d.push(h),e[h]=!0))}var d=[],e={};b.forEach(c);throw new eb(`${a}: `+d.map(fb).join([", "]));}function hb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function ib(a,b,c,d,e){var h=b.length;2>h&&M("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,f=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Z){f=!0;break}var l="void"!==b[0].name,n=h-2,m=Array(n),p=[],r=[];return function(){arguments.length!==n&&M(`function ${a} called with ${arguments.length} arguments, expected ${n} args!`);r.length=0;p.length=k?2:1;p[0]=e;if(k){var u=b[1].toWireType(r,this);p[1]=u}for(var t=0;t<n;++t)m[t]=
b[t+2].toWireType(r,arguments[t]),p.push(m[t]);t=d.apply(null,p);if(f)hb(r);else for(var x=k?1:2;x<b.length;x++){var H=1===x?u:m[x-2];null!==b[x].Z&&b[x].Z(H)}u=l?b[0].fromWireType(t):void 0;return u}}function kb(a,b){for(var c=[],d=0;d<a;d++)c.push(D[b+4*d>>2]);return c}
function lb(a,b,c){a instanceof Object||M(`${c} with invalid "this": ${a}`);a instanceof b.R.constructor||M(`${c} incompatible with "this" of type ${a.constructor.name}`);a.P.S||M(`cannot call emscripten binding method ${c} on deleted object`);return Xa(a.P.S,a.P.T.R,b.R)}
var Z=new function(){this.Y=[void 0];this.ka=[];this.get=function(a){return this.Y[a]};this.has=function(a){return void 0!==this.Y[a]};this.oa=function(a){var b=this.ka.pop()||this.Y.length;this.Y[b]=a;return b};this.pa=function(a){this.Y[a]=void 0;this.ka.push(a)}};function mb(a){a>=Z.la&&0===--Z.get(a).za&&Z.pa(a)}
var nb=a=>{a||M("Cannot use deleted val. handle = "+a);return Z.get(a).value},U=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return Z.oa({za:1,value:a})}};function Za(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function ob(a,b){switch(b){case 2:return function(c){return this.fromWireType(ka[c>>2])};case 3:return function(c){return this.fromWireType(la[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function pb(a,b,c){switch(b){case 0:return c?function(d){return ia[d]}:function(d){return A[d]};case 1:return c?function(d){return B[d>>1]}:function(d){return ja[d>>1]};case 2:return c?function(d){return C[d>>2]}:function(d){return D[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var qb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function rb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&ja[c];)++c;c<<=1;if(32<c-a&&qb)return qb.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=B[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function sb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)B[b>>1]=a.charCodeAt(e),b+=2;B[b>>1]=0;return b-d}function tb(a){return 2*a.length}
function ub(a,b){for(var c=0,d="";!(c>=b/4);){var e=C[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function vb(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var h=a.charCodeAt(e);if(55296<=h&&57343>=h){var k=a.charCodeAt(++e);h=65536+((h&1023)<<10)|k&1023}C[b>>2]=h;b+=4;if(b+4>c)break}C[b>>2]=0;return b-d}
function wb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function xb(a,b){var c=K[a];void 0===c&&M(b+" has unknown type "+fb(a));return c}var yb={},zb=[null,[],[]];function Ab(){var a=g.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentTrackEntry(),d=a.getCurrentEvent();a=a.getCurrentEventType();globalThis.TrackEntryListeners.emitListener(b,c,d,a)}g._spineListenerCallBackFromJS=Ab;
function Bb(){var a=g.SpineWasmUtil,b=a.getCurrentListenerID(),c=a.getCurrentEventType(),d=a.getCurrentTrackEntry();a=a.getCurrentEvent();globalThis.TrackEntryListeners.emitTrackEntryListener(b,d,a,c)}g._spineTrackListenerCallback=Bb;for(var Cb=Array(256),Db=0;256>Db;++Db)Cb[Db]=String.fromCharCode(Db);Da=Cb;L=g.BindingError=Ha("BindingError");Ia=g.InternalError=Ha("InternalError");
T.prototype.isAliasOf=function(a){if(!(this instanceof T&&a instanceof T))return!1;var b=this.P.T.R,c=this.P.S,d=a.P.T.R;for(a=a.P.S;b.U;)c=b.fa(c),b=b.U;for(;d.U;)a=d.fa(a),d=d.U;return b===d&&c===a};T.prototype.clone=function(){this.P.S||Ka(this);if(this.P.ea)return this.P.count.value+=1,this;var a=Ta,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.P;a=a(c.call(b,d,{P:{value:{count:e.count,da:e.da,ea:e.ea,S:e.S,T:e.T,W:e.W,X:e.X}}}));a.P.count.value+=1;a.P.da=!1;return a};
T.prototype["delete"]=function(){this.P.S||Ka(this);this.P.da&&!this.P.ea&&M("Object already scheduled for deletion");Ma(this);Na(this.P);this.P.ea||(this.P.W=void 0,this.P.S=void 0)};T.prototype.isDeleted=function(){return!this.P.S};T.prototype.deleteLater=function(){this.P.S||Ka(this);this.P.da&&!this.P.ea&&M("Object already scheduled for deletion");Q.push(this);1===Q.length&&R&&R(Qa);this.P.da=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(S).length};
g.getLiveInheritedInstances=function(){var a=[],b;for(b in S)S.hasOwnProperty(b)&&a.push(S[b]);return a};g.flushPendingDeletes=Qa;g.setDelayFunction=function(a){R=a;Q.length&&R&&R(Qa)};V.prototype.ta=function(a){this.na&&(a=this.na(a));return a};V.prototype.ma=function(a){this.ba&&this.ba(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=bb;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.ia?Sa(this.R.$,{T:this.va,S:c,X:this,W:a}):Sa(this.R.$,{T:this,S:a})}var c=this.ta(a);if(!c)return this.ma(a),null;var d=Ra(this.R,c);if(void 0!==d){if(0===d.P.count.value)return d.P.S=c,d.P.W=a,d.clone();d=d.clone();this.ma(a);return d}d=this.R.sa(c);d=Pa[d];if(!d)return b.call(this);d=this.ha?d.qa:d.pointerType;var e=Oa(c,this.R,d.R);return null===e?b.call(this):this.ia?Sa(d.R.$,{T:d,S:e,X:this,W:a}):Sa(d.R.$,{T:d,S:e})};
eb=g.UnboundTypeError=Ha("UnboundTypeError");Z.Y.push({value:void 0},{value:null},{value:!0},{value:!1});Z.la=Z.Y.length;g.count_emval_handles=function(){for(var a=0,b=Z.la;b<Z.Y.length;++b)void 0!==Z.Y[b]&&++a;return a};
var Fb={q:function(){return 0},z:function(){return 0},A:function(){},v:function(){},D:function(a,b,c,d,e){var h=Ca(c);b=I(b);P(a,{name:b,fromWireType:function(k){return!!k},toWireType:function(k,f){return f?d:e},argPackAdvance:8,readValueFromPointer:function(k){if(1===c)var f=ia;else if(2===c)f=B;else if(4===c)f=C;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(f[k>>h])},Z:null})},c:function(a,b,c,d,e,h,k,f,l,n,m,p,r){m=I(m);h=W(e,h);f&&(f=W(k,f));n&&(n=W(l,n));
r=W(p,r);var u=Fa(m);Va(u,function(){Y(`Cannot construct ${m} due to unbound types`,[d])});O([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var x=t.R;var H=x.$}else H=T.prototype;t=Ga(u,function(){if(Object.getPrototypeOf(this)!==N)throw new L("Use 'new' to construct "+m);if(void 0===z.aa)throw new L(m+" has no accessible constructor");var jb=z.aa[arguments.length];if(void 0===jb)throw new L(`Tried to invoke ctor of ${m} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(z.aa).toString()}) parameters instead!`);
return jb.apply(this,arguments)});var N=Object.create(H,{constructor:{value:t}});t.prototype=N;var z=new Wa(m,t,N,r,x,h,f,n);z.U&&(void 0===z.U.ga&&(z.U.ga=[]),z.U.ga.push(z));x=new V(m,z,!0,!1);H=new V(m+"*",z,!1,!1);var ca=new V(m+" const*",z,!1,!0);Pa[a]={pointerType:H,qa:ca};cb(u,t);return[x,H,ca]})},g:function(a,b,c,d,e,h,k){var f=kb(c,d);b=I(b);h=W(e,h);O([],[a],function(l){function n(){Y(`Cannot call ${m} due to unbound types`,f)}l=l[0];var m=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
var p=l.R.constructor;void 0===p[b]?(n.ca=c-1,p[b]=n):(Ua(p,b,m),p[b].V[c-1]=n);O([],f,function(r){r=ib(m,[r[0],null].concat(r.slice(1)),null,h,k);void 0===p[b].V?(r.ca=c-1,p[b]=r):p[b].V[c-1]=r;if(l.R.ga)for(const u of l.R.ga)u.constructor.hasOwnProperty(b)||(u.constructor[b]=r);return[]});return[]})},i:function(a,b,c,d,e,h,k,f){b=I(b);h=W(e,h);O([],[a],function(l){l=l[0];var n=`${l.name}.${b}`,m={get:function(){Y(`Cannot access ${n} due to unbound types`,[c])},enumerable:!0,configurable:!0};m.set=
f?()=>{Y(`Cannot access ${n} due to unbound types`,[c])}:()=>{M(`${n} is a read-only property`)};Object.defineProperty(l.R.constructor,b,m);O([],[c],function(p){p=p[0];var r={get:function(){return p.fromWireType(h(d))},enumerable:!0};f&&(f=W(k,f),r.set=u=>{var t=[];f(d,p.toWireType(t,u));hb(t)});Object.defineProperty(l.R.constructor,b,r);return[]});return[]})},d:function(a,b,c,d,e,h){0<b||y();var k=kb(b,c);e=W(d,e);O([],[a],function(f){f=f[0];var l=`constructor ${f.name}`;void 0===f.R.aa&&(f.R.aa=
[]);if(void 0!==f.R.aa[b-1])throw new L(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.R.aa[b-1]=()=>{Y(`Cannot construct ${f.name} due to unbound types`,k)};O([],k,function(n){n.splice(1,0,null);f.R.aa[b-1]=ib(l,n,null,e,h);return[]});return[]})},a:function(a,b,c,d,e,h,k,f){var l=kb(c,d);b=I(b);h=W(e,h);O([],[a],function(n){function m(){Y(`Cannot call ${p} due to unbound types`,
l)}n=n[0];var p=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);f&&n.R.wa.push(b);var r=n.R.$,u=r[b];void 0===u||void 0===u.V&&u.className!==n.name&&u.ca===c-2?(m.ca=c-2,m.className=n.name,r[b]=m):(Ua(r,b,p),r[b].V[c-2]=m);O([],l,function(t){t=ib(p,t,n,h,k);void 0===r[b].V?(t.ca=c-2,r[b]=t):r[b].V[c-2]=t;return[]});return[]})},b:function(a,b,c,d,e,h,k,f,l,n){b=I(b);e=W(d,e);O([],[a],function(m){m=m[0];var p=`${m.name}.${b}`,r={get:function(){Y(`Cannot access ${p} due to unbound types`,
[c,k])},enumerable:!0,configurable:!0};r.set=l?()=>{Y(`Cannot access ${p} due to unbound types`,[c,k])}:()=>{M(p+" is a read-only property")};Object.defineProperty(m.R.$,b,r);O([],l?[c,k]:[c],function(u){var t=u[0],x={get:function(){var N=lb(this,m,p+" getter");return t.fromWireType(e(h,N))},enumerable:!0};if(l){l=W(f,l);var H=u[1];x.set=function(N){var z=lb(this,m,p+" setter"),ca=[];l(n,z,H.toWireType(ca,N));hb(ca)}}Object.defineProperty(m.R.$,b,x);return[]});return[]})},C:function(a,b){b=I(b);P(a,
{name:b,fromWireType:function(c){var d=nb(c);mb(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:bb,Z:null})},r:function(a,b,c){c=Ca(c);b=I(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},argPackAdvance:8,readValueFromPointer:ob(b,c),Z:null})},e:function(a,b,c,d,e){b=I(b);-1===e&&(e=4294967295);e=Ca(c);var h=f=>f;if(0===d){var k=32-8*c;h=f=>f<<k>>>k}c=b.includes("unsigned")?function(f,l){return l>>>0}:function(f,l){return l};
P(a,{name:b,fromWireType:h,toWireType:c,argPackAdvance:8,readValueFromPointer:pb(b,e,0!==d),Z:null})},f:function(a,b,c){function d(h){h>>=2;var k=D;return new e(k.buffer,k[h+1],k[h])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=I(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ua:!0})},m:function(a,b){b=I(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=D[d>>2],h=d+4;if(c)for(var k=h,f=0;f<=e;++f){var l=
h+f;if(f==e||0==A[l]){k=k?Ba(A,k,l-k):"";if(void 0===n)var n=k;else n+=String.fromCharCode(0),n+=k;k=l+1}}else{n=Array(e);for(f=0;f<e;++f)n[f]=String.fromCharCode(A[h+f]);n=n.join("")}X(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var h,k="string"==typeof e;k||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||M("Cannot pass non-string to std::string");var f;if(c&&k)for(h=f=0;h<e.length;++h){var l=e.charCodeAt(h);127>=l?f++:2047>=
l?f+=2:55296<=l&&57343>=l?(f+=4,++h):f+=3}else f=e.length;h=f;f=Eb(4+h+1);l=f+4;D[f>>2]=h;if(c&&k){if(k=l,l=h+1,h=A,0<l){l=k+l-1;for(var n=0;n<e.length;++n){var m=e.charCodeAt(n);if(55296<=m&&57343>=m){var p=e.charCodeAt(++n);m=65536+((m&1023)<<10)|p&1023}if(127>=m){if(k>=l)break;h[k++]=m}else{if(2047>=m){if(k+1>=l)break;h[k++]=192|m>>6}else{if(65535>=m){if(k+2>=l)break;h[k++]=224|m>>12}else{if(k+3>=l)break;h[k++]=240|m>>18;h[k++]=128|m>>12&63}h[k++]=128|m>>6&63}h[k++]=128|m&63}}h[k]=0}}else if(k)for(k=
0;k<h;++k)n=e.charCodeAt(k),255<n&&(X(l),M("String has UTF-16 code units that do not fit in 8 bits")),A[l+k]=n;else for(k=0;k<h;++k)A[l+k]=e[k];null!==d&&d.push(X,f);return f},argPackAdvance:8,readValueFromPointer:bb,Z:function(d){X(d)}})},n:function(a,b,c){c=I(c);if(2===b){var d=rb;var e=sb;var h=tb;var k=()=>ja;var f=1}else 4===b&&(d=ub,e=vb,h=wb,k=()=>D,f=2);P(a,{name:c,fromWireType:function(l){for(var n=D[l>>2],m=k(),p,r=l+4,u=0;u<=n;++u){var t=l+4+u*b;if(u==n||0==m[t>>f])r=d(r,t-r),void 0===
p?p=r:(p+=String.fromCharCode(0),p+=r),r=t+b}X(l);return p},toWireType:function(l,n){"string"!=typeof n&&M(`Cannot pass non-string to C++ string type ${c}`);var m=h(n),p=Eb(4+m+b);D[p>>2]=m>>f;e(n,p+4,m+b);null!==l&&l.push(X,p);return p},argPackAdvance:8,readValueFromPointer:bb,Z:function(l){X(l)}})},E:function(a,b){b=I(b);P(a,{Ba:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},k:function(a,b,c){a=nb(a);b=xb(b,"emval::as");var d=[],e=U(d);D[c>>2]=e;return b.toWireType(d,
a)},h:mb,l:function(a,b){a=nb(a);b=nb(b);return U(a[b])},t:function(a){var b=yb[a];return U(void 0===b?I(a):b)},j:function(a){var b=nb(a);hb(b);mb(a)},s:function(a,b){a=xb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},o:function(){y("")},B:function(a,b,c){A.copyWithin(a,b,b+c)},w:function(a){var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);a:{e=e.min.call(e,2147483648,d+(65536-d%65536)%65536)-
fa.buffer.byteLength+65535>>>16;try{fa.grow(e);ma();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},p:function(){return 52},y:function(){return 52},u:function(){return 70},x:function(a,b,c,d){for(var e=0,h=0;h<c;h++){var k=D[b>>2],f=D[b+4>>2];b+=8;for(var l=0;l<f;l++){var n=A[k+l],m=zb[a];0===n||10===n?((1===a?ea:v)(Ba(m,0)),m.length=0):m.push(n)}e+=f}D[d>>2]=e;return 0},G:Ab,F:Bb};
(function(){function a(c){c=c.exports;g.asm=c;fa=g.asm.H;ma();na=g.asm.J;pa.unshift(g.asm.I);E--;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(0==E&&(null!==sa&&(clearInterval(sa),sa=null),F)){var d=F;F=null;d()}return c}var b={a:Fb};E++;g.monitorRunDependencies&&g.monitorRunDependencies(E);if(g.instantiateWasm)try{return g.instantiateWasm(b,a)}catch(c){v("Module.instantiateWasm callback failed with error: "+c),ba(c)}ya(b,function(c){a(c.instance)}).catch(ba);return{}})();
function Eb(){return(Eb=g.asm.K).apply(null,arguments)}function X(){return(X=g.asm.L).apply(null,arguments)}function gb(){return(gb=g.asm.M).apply(null,arguments)}g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.N).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.O).apply(null,arguments)};var Gb;F=function Hb(){Gb||Ib();Gb||(F=Hb)};
function Ib(){function a(){if(!Gb&&(Gb=!0,g.calledRun=!0,!ha)){za(pa);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();qa.unshift(b)}za(qa)}}if(!(0<E)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)ra();za(oa);0<E||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);a()},1)):a())}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();Ib();


  return spineWasm.ready
}

);
})();
export default spineWasm;